const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Timer,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.AddCost,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Pathfinding.Acts.RegenerateObjectRegion,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Behaviors.Flash.Acts.Flash
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Obstacle: 0},
	{arrived: 0},
	{blockedBy: 0},
	{priorityPass: 0},
	{inDeadBlock: 0},
	{NPC_Group: 0},
	{distanceToTarget: 0},
	{targetX: 0},
	{targetY: 0},
	{npc: 0},
	{CellMarker: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Node: 0},
	{Touch: 0},
	{Text: 0},
	{Text2: 0},
	{TiledBackground: 0},
	{npcSpot: 0},
	{Timer: 0},
	{Pathfinding: 0},
	{Flash: 0},
	{NPCs: 0},
	{Nodes: 0},
	{npcTargets: 0},
	{recalculatePath: 0},
	{group: 0},
	{radius: 0}
];

self.InstanceType = {
	Obstacle: class extends self.ISpriteInstance {},
	npc: class extends self.ISpriteInstance {},
	CellMarker: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Node: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	npcSpot: class extends self.ISpriteInstance {},
	NPCs: class extends self.ISpriteInstance {},
	Nodes: class extends self.ISpriteInstance {},
	npcTargets: class extends self.ISpriteInstance {}
}